### ISSUE TITLE
Alternatives projects

### ISSUE THREAD

**Issue by gtirloni** [hansfbaier/mini-keyboard-configurator#1]
Thanks for working on this and I understand you won't have time to work on issues so I'd just like to mention alternative projects that I have tried (because I couldn't get this one to work on Debian 13 -- I can submit a proper bug report if you think it'd be useful):

- https://github.com/kriomant/ch57x-keyboard-tool - CLI tool that uses YAML configuration and worked fine with by 12-key CH57x-based keyboard

Sample config:

```yaml
orientation: normal
rows: 3
columns: 4
knobs: 2

layers:
  - buttons:
      - ['a','b','c','d']
      - ['x','y','z','X']
      - ['1','2','3','4']
    knobs:
      - ccw: 'wheeldown'
        press: 'click'
        cw: 'wheelup'
      - ccw: 'shift-wheeldown'
        press: 'shift-click'
        cw: 'shift-wheelup'
```

- https://github.com/jonnytest1/minikeyboard - The original software for Windows, it kind of runs on Wine 8.0 but the USB device is not seen properly so you can't upload the configuration
